const DEFAULT_BLOCKS=[{duration:15000,repeats:10,label:'Set one'},{duration:30000,repeats:20,label:'Set two'}];const SET_KEY='spa-bell-set-v2',VOL_KEY='spa-bell-volume-v1';let blocks=load(SET_KEY)||DEFAULT_BLOCKS,volume=Number(localStorage.getItem(VOL_KEY)??.55),audio=createBellAudio(),timer;
const $=id=>document.getElementById(id), fmt=ms=>{let s=Math.ceil(ms/1000),m=Math.floor(s/60);return `${String(m).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`};
function load(k){try{return JSON.parse(localStorage.getItem(k))}catch{return null}}function normalize(){blocks=blocks.map(b=>({duration:Math.max(1000,Number(b.duration)||60000),repeats:Math.max(1,Math.round(Number(b.repeats)||1)),label:String(b.label||'')}))}
function save(){localStorage.setItem(SET_KEY,JSON.stringify(blocks));localStorage.setItem(VOL_KEY,String(volume))}
function renderSet(){const list=$('set-list');list.innerHTML='';blocks.forEach((b,i)=>{const el=document.createElement('div');el.className='block';el.innerHTML=`<span class="block-number">${String(i+1).padStart(2,'0')}</span><label class="label-field"><span class="field-label">Name</span><input data-i="${i}" data-key="label" value="${escapeHtml(b.label)}" placeholder="Quiet focus"></label><label><span class="field-label">Duration</span><input data-i="${i}" data-key="duration" type="number" min="1" step="1" value="${b.duration/1000}"></label><label><span class="field-label">Repeats</span><input data-i="${i}" data-key="repeats" type="number" min="1" step="1" value="${b.repeats}"></label><div class="block-actions"><button class="icon-button" data-action="up" data-i="${i}" aria-label="Move interval up">↑</button><button class="icon-button" data-action="down" data-i="${i}" aria-label="Move interval down">↓</button><button class="icon-button" data-action="delete" data-i="${i}" aria-label="Delete interval">×</button></div>`;list.append(el)})}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function update(s){if(s.done)return;$('timer-display').textContent=fmt(s.remaining);const b=blocks[s.blockIndex]||blocks[0];$('current-block').textContent=`${b.label||'Untitled interval'} · ${Math.ceil(s.remaining/1000)} seconds`;$('round-progress').textContent=`Round ${s.roundIndex+1} of ${s.roundCount} · Block ${s.blockIndex+1} of ${s.blockCount}`;$('progress-bar').style.width=`${(s.elapsed/s.duration)*100}%`}
function boot(){normalize();renderSet();$('volume-input').value=volume;$('volume-value').textContent=`${Math.round(volume*100)}%`;audio.setVolume(volume);timer=new IntervalTimer({onTick:update,onBell:()=>{audio.play();document.body.classList.remove('bell');void document.body.offsetWidth;document.body.classList.add('bell');if(navigator.vibrate)navigator.vibrate(45)},onComplete:()=>{$('timer-status').textContent='SET COMPLETE · WELL DONE';$('start-button').textContent='Start again'},onStateChange:running=>{$('timer-status').textContent=running?'LISTENING FOR THE NEXT BELL':'PAUSED';$('start-button').disabled=running;$('pause-button').disabled=!running}});timer.setBlocks(blocks);update(timer.getSnapshot())}
$('start-button').addEventListener('click',()=>timer.start());$('pause-button').addEventListener('click',()=>timer.pause());$('reset-button').addEventListener('click',()=>{timer.setBlocks(blocks);$('timer-status').textContent='READY WHEN YOU ARE';$('start-button').textContent='Start the set'});$('skip-button').addEventListener('click',()=>timer.skip());$('volume-input').addEventListener('input',e=>{volume=Number(e.target.value);$('volume-value').textContent=`${Math.round(volume*100)}%`;audio.setVolume(volume);save()});$('add-block-button').addEventListener('click',()=>{blocks.push({duration:60000,repeats:1,label:'New interval'});save();renderSet();boot()});$('set-list').addEventListener('change',e=>{const i=Number(e.target.dataset.i),key=e.target.dataset.key;if(!Number.isNaN(i)&&key){blocks[i][key]=key==='label'?e.target.value:(key==='duration'?Math.max(1000,Number(e.target.value)*1000):Math.max(1,Math.round(Number(e.target.value))));normalize();save();renderSet();boot()}});$('set-list').addEventListener('click',e=>{const btn=e.target.closest('[data-action]');if(!btn)return;const i=Number(btn.dataset.i),a=btn.dataset.action;if(a==='delete'&&blocks.length>1)blocks.splice(i,1);if(a==='up'&&i>0)[blocks[i-1],blocks[i]]=[blocks[i],blocks[i-1]];if(a==='down'&&i<blocks.length-1)[blocks[i+1],blocks[i]]=[blocks[i],blocks[i+1]];save();renderSet();boot()});boot();
